name: playerfactions

on:
  push:
    branches: ['master']
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: mirror
      run: ./mirror.sh
      env:
        source_repo: https://git.leagueh.xyz/katp32/playerfactions.git
        github_repo: playerfactions.git
        branch: master
        access_token: ${{ secrets.ACCESS_TOKEN }}
